import Link from "next/link";
import MarketingHeader from "@/components/MarketingHeader";
import { ArrowRight, Download, FileText, ExternalLink } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Resources — CFOlytics",
  description: "Download sample financial reports, browse product screenshots, and learn how CFOlytics works — all in one place.",
};

const ALL_SCREENSHOTS = [
  { img: "/marketing-photos/Overview/OVER-1.png", name: "Overview Dashboard", category: "Core" },
  { img: "/marketing-photos/AI CFO Chat/AI-CFO-CHAT-1.png", name: "AI CFO Chat", category: "AI" },
  { img: "/marketing-photos/Anomaly Hub/AH-1.png", name: "Anomaly Resolution Hub", category: "AI" },
  { img: "/marketing-photos/Accounts Payables/AP-1.png", name: "Accounts Payable", category: "Core" },
  { img: "/marketing-photos/Budgeting/B-1.png", name: "Budgeting", category: "Finance" },
  { img: "/marketing-photos/Finance Report/FR-1.png", name: "Financial Reports", category: "Finance" },
  { img: "/marketing-photos/KPI Builder/KPI-1.png", name: "KPI Builder", category: "Finance" },
  { img: "/marketing-photos/Scenarios/SC-1.png", name: "Scenarios", category: "AI" },
  { img: "/marketing-photos/Connectors/C-1.png", name: "Connectors", category: "Core" },
  { img: "/marketing-photos/Upload Data/UD-1.png", name: "Data Upload", category: "Core" },
  { img: "/marketing-photos/Intelligence/I-1.png", name: "Intelligence Feed", category: "AI" },
  { img: "/marketing-photos/Data Query (AI)/DQ-1.png", name: "AI Data Query", category: "AI" },
  { img: "/marketing-photos/Org Chat/ORG-1.png", name: "Org Chat", category: "Collaboration" },
  { img: "/marketing-photos/Notifications/N-1.png", name: "Notifications", category: "Collaboration" },
  { img: "/marketing-photos/Audit Trails/AT-1.png", name: "Audit Trails", category: "Governance" },
  { img: "/marketing-photos/Permissions/P-1.png", name: "Permissions (RBAC)", category: "Governance" },
  { img: "/marketing-photos/Team Directory/TD-1.png", name: "Team Directory", category: "Governance" },
  { img: "/marketing-photos/Workspaces/W-1.png", name: "Workspaces", category: "Governance" },
  { img: "/marketing-photos/Workspace Settings/WS-1.png", name: "Workspace Settings", category: "Governance" },
  { img: "/marketing-photos/Excel Add-in/EA-1.png", name: "Excel Add-in", category: "Core" },
];

const CATEGORY_COLORS: Record<string, string> = {
  Core: "text-blue-400 bg-blue-500/10 border-blue-500/20",
  AI: "text-purple-400 bg-purple-500/10 border-purple-500/20",
  Finance: "text-amber-400 bg-amber-500/10 border-amber-500/20",
  Collaboration: "text-emerald-400 bg-emerald-500/10 border-emerald-500/20",
  Governance: "text-rose-400 bg-rose-500/10 border-rose-500/20",
};

export default function ResourcesPage() {
  return (
    <div className="min-h-screen bg-[#0c0f17] text-white">
      <MarketingHeader />

      <div className="mx-auto max-w-7xl px-6 pt-32 pb-24">

        {/* Header */}
        <div className="flex items-center gap-4 mb-6">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-slate-500">Resources</p>
          <div className="flex-1 h-px bg-white/5" />
        </div>
        <h1 className="text-4xl lg:text-5xl font-bold text-white mb-4 leading-tight">
          See CFOlytics before<br />you sign up.
        </h1>
        <p className="text-xl text-slate-400 max-w-2xl mb-16">
          Every screen, every report, every AI feature. Browse actual product screenshots and download a sample financial report generated by the platform.
        </p>

        {/* PDF Download Card */}
        <div className="grid md:grid-cols-2 gap-8 mb-20">
          <div className="rounded-2xl border border-blue-500/20 bg-gradient-to-br from-blue-500/5 to-indigo-500/5 p-8 flex flex-col justify-between">
            <div>
              <div className="flex items-center gap-3 mb-6">
                <div className="p-3 rounded-xl bg-blue-500/10 border border-blue-500/20">
                  <FileText className="h-6 w-6 text-blue-400" />
                </div>
                <div>
                  <p className="text-sm font-bold text-white">Sample Financial Report</p>
                  <p className="text-xs text-slate-500">Generated by CFOlytics AI</p>
                </div>
              </div>
              <p className="text-slate-400 text-sm leading-relaxed mb-4">
                A complete AI-generated financial report package including P&L Statement, Cash Flow
                Analysis, Balance Sheet, Variance Report, and an AI narrative summary — exactly what
                your team will receive after processing your first financial data upload.
              </p>
              <ul className="space-y-2 mb-8">
                {["P&L Statement", "Cash Flow Statement", "Balance Sheet", "Variance Analysis", "AI Executive Summary"].map((item) => (
                  <li key={item} className="flex items-center gap-2 text-sm text-slate-400">
                    <span className="h-1.5 w-1.5 rounded-full bg-blue-400 flex-shrink-0" />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
            <a
              href="/marketing-photos/Finance Report/FR-1.pdf"
              target="_blank"
              className="inline-flex items-center gap-2 rounded-xl bg-white text-[#0c0f17] px-6 py-3 text-sm font-bold self-start transition-all hover:bg-slate-100 shadow-xl shadow-white/10"
            >
              <Download className="h-4 w-4" />
              Download Sample PDF
            </a>
          </div>

          <div className="rounded-2xl overflow-hidden border border-[#1e2637] shadow-2xl group hover:border-blue-500/20 transition-all">
            <div className="px-4 py-3 bg-[#111827] border-b border-white/5 flex items-center justify-between">
              <span className="text-xs font-medium text-slate-400">CFOlytics Financial Report — Preview</span>
              <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-semibold">AI Generated</span>
            </div>
            <img src="/marketing-photos/Finance Report/FR-1.png" alt="Sample Financial Report" className="w-full object-cover object-top group-hover:scale-[1.005] transition-transform duration-700" />
          </div>
        </div>

        {/* Full Finance Report Walkthrough */}
        <div className="mb-20">
          <div className="flex items-center gap-4 mb-8">
            <h2 className="text-xl font-bold text-white uppercase tracking-wider">Financial Report — All Pages</h2>
            <div className="flex-1 h-px bg-white/10" />
          </div>
          <div className="grid md:grid-cols-3 gap-5">
            {[
              { img: "/marketing-photos/Finance Report/FR-2.png", label: "P&L Statement" },
              { img: "/marketing-photos/Finance Report/FR-3.png", label: "Cash Flow Statement" },
              { img: "/marketing-photos/Finance Report/FR-4.png", label: "Balance Sheet" },
              { img: "/marketing-photos/Finance Report/FR-5.png", label: "Variance Analysis" },
              { img: "/marketing-photos/Finance Report/FR-6.png", label: "AI Executive Summary" },
            ].map((s) => (
              <div key={s.label} className="rounded-xl overflow-hidden border border-[#1e2637] group hover:border-blue-500/30 transition-all shadow-lg">
                <div className="px-4 py-2.5 bg-[#111827] border-b border-white/5">
                  <span className="text-xs font-medium text-slate-400">{s.label}</span>
                </div>
                <img src={s.img} alt={s.label} className="w-full object-cover object-top group-hover:scale-[1.01] transition-transform duration-500" />
              </div>
            ))}
          </div>
        </div>

        {/* Full 20-module screenshot gallery */}
        <div className="mb-16">
          <div className="flex items-center gap-4 mb-8">
            <h2 className="text-xl font-bold text-white uppercase tracking-wider">All 20 Platform Modules</h2>
            <div className="flex-1 h-px bg-white/10" />
          </div>
          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-5">
            {ALL_SCREENSHOTS.map((s) => (
              <div key={s.name} className="group rounded-xl overflow-hidden border border-[#1e2637] hover:border-white/20 transition-all shadow-lg">
                <div className="h-40 overflow-hidden bg-[#0a0d14] border-b border-white/5 relative">
                  <img src={s.img} alt={s.name} className="w-full h-full object-cover object-top opacity-85 group-hover:opacity-100 group-hover:scale-[1.03] transition-all duration-500" />
                  <div className="absolute bottom-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity duration-300">
                    <span className={`text-[9px] font-bold uppercase px-2 py-0.5 rounded-full border ${CATEGORY_COLORS[s.category]}`}>{s.category}</span>
                  </div>
                </div>
                <div className="p-3 bg-[#0f172a]">
                  <p className="text-xs font-semibold text-white">{s.name}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* CTA */}
        <div className="border-t border-white/5 pt-16 text-center">
          <h2 className="text-3xl font-bold text-white mb-4">Ready to try it on your own data?</h2>
          <p className="text-slate-400 mb-8">Upload any Excel or CSV and your AI financial intelligence dashboard is live in under 10 minutes.</p>
          <div className="flex flex-wrap gap-4 justify-center">
            <Link href="/sign-up" className="inline-flex items-center gap-2 rounded-xl bg-white text-[#0c0f17] px-8 py-4 text-sm font-bold transition-all hover:bg-slate-100 shadow-xl shadow-white/10">
              Get started free <ArrowRight className="h-4 w-4" />
            </Link>
            <Link href="/features" className="inline-flex items-center gap-2 rounded-xl border border-white/10 px-8 py-4 text-sm font-medium text-slate-300 transition-all hover:border-white/25 hover:text-white">
              Browse all features <ExternalLink className="h-4 w-4" />
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}
