# Generated by Django 6.0.2 on 2026-03-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnomalyLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("is_resolved", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ForecastResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("forecast_date", models.DateField()),
                (
                    "predicted_revenue",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "predicted_expenses",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "lower_bound",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "upper_bound",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="KPISnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("period", models.CharField(max_length=7)),
                (
                    "total_revenue",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "net_profit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "profit_margin",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                (
                    "burn_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "runway_months",
                    models.DecimalField(decimal_places=1, default=0, max_digits=6),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Recommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("detail", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("action", "Action Required"),
                        ],
                        default="info",
                        max_length=10,
                    ),
                ),
                (
                    "related_kpi",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
