# Generated by Django 6.0.2 on 2026-03-30 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_uploadedfile_parsedrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("tally", "Tally Prime"),
                            ("razorpay", "Razorpay"),
                            ("google_sheets", "Google Sheets"),
                            ("zoho", "Zoho Books"),
                            ("manual_csv", "Manual CSV Upload"),
                        ],
                        max_length=50,
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("config", models.JSONField(default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("bot_id", "source_type", "display_name")},
            },
        ),
        migrations.CreateModel(
            name="ConnectorSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("records_fetched", models.IntegerField(default=0)),
                ("records_inserted", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("currency_used", models.CharField(default="INR", max_length=10)),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=6, default=1.0, max_digits=12),
                ),
                ("synced_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="api.datasource",
                    ),
                ),
            ],
        ),
    ]
