# Generated by Django 6.0.2 on 2026-03-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_sprint6_connectors"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("category", models.CharField(max_length=255)),
                (
                    "allocated_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("month_year", models.CharField(max_length=7)),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("bot_id", "month_year", "category"),
                        name="unique_active_budget",
                    )
                ],
            },
        ),
    ]
