# Generated by Django 6.0.2 on 2026-03-31 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(max_length=100)),
                ("po_number", models.CharField(max_length=100)),
                ("vendor_name", models.CharField(max_length=255)),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=15),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("bot_id", "po_number")},
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(max_length=100)),
                ("vendor_name", models.CharField(max_length=255)),
                (
                    "invoice_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=15, null=True
                    ),
                ),
                ("date_issued", models.DateField(blank=True, null=True)),
                (
                    "line_items",
                    models.JSONField(
                        default=list,
                        help_text="[{'description': '...', 'amount': 100}]",
                    ),
                ),
                ("gl_code", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "fraud_confidence_score",
                    models.IntegerField(default=0, help_text="0 to 100"),
                ),
                (
                    "fraud_flags",
                    models.JSONField(
                        default=list,
                        help_text="List of reasons e.g., 'Math mismatch', 'Unregistered vendor'",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        default="pending_approval",
                        max_length=50,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_po",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
