# Generated by Django 6.0.2 on 2026-03-31 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_purchaseorder_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="additional_notes",
            field=models.TextField(
                blank=True,
                help_text="Any extra text, terms, or context extracted from the document.",
                null=True,
            ),
        ),
    ]
