# Generated by Django 6.0.2 on 2026-03-31 10:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_invoice_additional_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
    ]
