# Generated by Django 6.0.2 on 2026-04-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_notificationmeta"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("raw_category", models.CharField(max_length=255)),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("Revenue", "Revenue"),
                            ("COGS", "Cost of Goods Sold (COGS)"),
                            ("OPEX", "Operating Expense (OPEX)"),
                            ("Asset", "Asset"),
                            ("Liability", "Liability"),
                            ("Equity", "Equity"),
                            ("Other", "Other/Ignored"),
                        ],
                        default="Other",
                        max_length=50,
                    ),
                ),
                (
                    "standardized_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("bot_id", "raw_category")},
            },
        ),
    ]
