# Generated by Django 6.0.2 on 2026-04-01 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_categorymapping"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("user_email", models.CharField(max_length=255)),
                ("action", models.CharField(max_length=255)),
                ("resource_type", models.CharField(blank=True, max_length=255)),
                ("resource_id", models.CharField(blank=True, max_length=255)),
                ("details", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.AddField(
            model_name="anomalylog",
            name="assigned_to",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="anomalylog",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in-review", "In Review"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AnomalyComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(max_length=255)),
                ("user_email", models.CharField(max_length=255)),
                ("text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "anomaly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="api.anomalylog",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserFeaturePermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(db_index=True, max_length=255)),
                ("user_email", models.CharField(blank=True, max_length=255)),
                ("can_view_reports", models.BooleanField(default=True)),
                ("can_upload_data", models.BooleanField(default=False)),
                ("can_manage_budgets", models.BooleanField(default=False)),
                ("can_manage_ap", models.BooleanField(default=False)),
                ("can_run_simulations", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("bot_id", "user_id")},
            },
        ),
    ]
