# Generated by Django 6.0.2 on 2026-04-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_auditevent_anomalylog_assigned_to_anomalylog_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalTarget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                (
                    "workspace_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("goal_name", models.CharField(max_length=255)),
                ("target_value", models.DecimalField(decimal_places=2, max_digits=15)),
                ("period", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="OrgChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(db_index=True, max_length=255)),
                (
                    "workspace_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("user_name", models.CharField(max_length=255)),
                ("user_avatar", models.TextField(blank=True, null=True)),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("entity_type", models.CharField(default="Corporate", max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
