# Generated by Django 6.0.2 on 2026-04-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_goaltarget_orgchatmessage_workspace"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="workspace",
            name="is_active",
        ),
        migrations.AddField(
            model_name="workspace",
            name="region",
            field=models.CharField(default="Asia-Pacific", max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="secure_key",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="workspace",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("closed", "Closed"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
