# Generated by Django 6.0.2 on 2026-04-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_sprint16_workspace_status_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("reviewed", "Reviewed"),
                    ("flagged", "Flagged"),
                    ("approved", "Approved"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
