# Generated by Django 6.0.2 on 2026-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_developerapikey_inboundemaillog_invoicethread"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomKPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("name", models.CharField(max_length=100)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("formula", models.TextField()),
                ("unit", models.CharField(default="$", max_length=20)),
                ("icon", models.CharField(default="📊", max_length=10)),
                ("color", models.CharField(default="indigo", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
    ]
