# Generated by Django 6.0.2 on 2026-04-16 04:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_customkpi"),
    ]

    operations = [
        migrations.CreateModel(
            name="NLQueryHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bot_id", models.CharField(db_index=True, max_length=255)),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("question", models.TextField()),
                (
                    "result",
                    models.JSONField(
                        help_text="Stores the generated AI output dict (columns, rows, success, etc)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterField(
            model_name="anomalylog",
            name="detected_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="budget",
            name="month_year",
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_approval", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("paid", "Paid"),
                ],
                db_index=True,
                default="pending_approval",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="kpisnapshot",
            name="period",
            field=models.CharField(db_index=True, max_length=7),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="category",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
